# coding: utf-8

"""
    InCountry

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2019-01-15T16:20:14Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import incountry
from incountry.com.incountry.model.data import Data  # noqa: E501
from incountry.rest import ApiException


class TestData(unittest.TestCase):
    """Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testData(self):
        """Test Data"""
        # FIXME: construct object with mandatory attributes with example values
        # model = incountry.models.data.Data()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
