# coding: utf-8

"""
    InCountry

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2019-01-15T16:20:14Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import incountry
from com.incountry.api.default_api import DefaultApi  # noqa: E501
from incountry.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = com.incountry.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_post(self):
        """Test case for delete_post

        """
        pass

    def test_keylookup_post(self):
        """Test case for keylookup_post

        """
        pass

    def test_lookup_post(self):
        """Test case for lookup_post

        """
        pass

    def test_read_post(self):
        """Test case for read_post

        """
        pass

    def test_write_post(self):
        """Test case for write_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
